default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: steam_stalker_dev

test:
  <<: *default
  database: steam_stalker_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
 
